

function TangoGui(tango)

    if nargin == 1
        if ~isa(tango,'Tango')
            error('Expected argument 1 to be a valid Tango');
        else
            createobj = false;
        end
    else
        createobj = true;
    end

    % Création de l'objet Figure
    figure('units','pixels',...
        'position',[250 250 500 500],...
        'color',[0.925 0.913 0.687],...
        'numbertitle','off',...
        'name','Tango Control',...
        'menubar','none',...
        'tag','interface');
    
    % X-Y
    
    % Panel X-Y
    XYp = uipanel('Title','Contrôles X-Y','FontSize',12,...
             'BackgroundColor','white',...
             'Position',[0 .5 .5 .5]);
    

    % Bouton retour maison
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.4 0.4 0.2 0.2],...
        'string','0',...    
        'callback',{@gotopos,[[0,0,0,0]]},...
        'tag','0');
    % Boutons XY
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.6 0.4 0.2 0.2],...
        'string','X+',...    
        'callback',{@increasePos,[1,0,0,0]},...
        'tag','0');
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.8 0.4 0.2 0.2],...
        'string','X++',...    
        'callback',{@increasePos,[10,0,0,0]},...
        'tag','0');
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.2 0.4 0.2 0.2],...
        'string','X-',...    
        'callback',{@increasePos,[-1,0,0,0]},...
        'tag','0');
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0 0.4 0.2 0.2],...
        'string','X--',...    
        'callback',{@increasePos,[-10,0,0,0]},...
        'tag','0');
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.4 0.6 0.2 0.2],...
        'string','Y+',...    
        'callback',{@increasePos,[0,1,0,0]},...
        'tag','0');
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.4 0.8 0.2 0.2],...
        'string','Y++',...    
        'callback',{@increasePos,[0,10,0,0]},...
        'tag','0');
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.4 0.2 0.2 0.2],...
        'string','Y-',...    
        'callback',{@increasePos,[0,-1,0,0]},...
        'tag','0');
    
    uicontrol('style','pushbutton',...
        'Parent',XYp, ...
        'units','normalized',...
        'position',[0.4 0. 0.2 0.2],...
        'string','Y--',...    
        'callback',{@increasePos,[0,-10,0,0]},...
        'tag','0');

    
    function gotopos(~,~,pos)
        tango.setPos(pos);
    end

    function increasePos(~,~,dp)
       tango.displace(dp);
    end
end

